const fs = require('fs');
const path = require('path');

const examples = {
  "abandon": { "example": "They had to abandon the sinking ship.", "example_translation": "그들은 침몰하는 배를 버려야 했다." },
  "ability": { "example": "He has the ability to learn quickly.", "example_translation": "그는 빨리 배우는 능력을 가지고 있다." },
  "abolish": { "example": "The government plans to abolish the tax.", "example_translation": "정부는 그 세금을 폐지할 계획이다." },
  "absence": { "example": "Her absence was noticed by everyone.", "example_translation": "그녀의 부재는 모든 사람의 눈에 띄었다." },
  "absolute": { "example": "I have absolute confidence in her.", "example_translation": "나는 그녀를 전적으로 신뢰한다." },
  "absolutely": { "example": "You are absolutely right.", "example_translation": "당신 말이 전적으로 옳습니다." },
  "absorb": { "example": "Sponges absorb water easily.", "example_translation": "스펀지는 물을 쉽게 흡수한다." },
  "abstract": { "example": "He is famous for his abstract paintings.", "example_translation": "그는 추상화로 유명하다." },
  "absurd": { "example": "It is an absurd idea.", "example_translation": "그것은 터무니없는 생각이다." },
  "absurdity": { "example": "The absurdity of the situation made everyone laugh.", "example_translation": "상황의 불합리함이 모두를 웃게 만들었다." },
  "abundance": { "example": "There is an abundance of food here.", "example_translation": "이곳에는 식량이 풍부하다." },
  "abundant": { "example": "The country has abundant natural resources.", "example_translation": "그 나라는 천연자원이 풍부하다." },
  "abuse": { "example": "He was accused of power abuse.", "example_translation": "그는 권력 남용으로 고발당했다." },
  "accelerate": { "example": "The car began to accelerate.", "example_translation": "차가 가속하기 시작했다." },
  "accept": { "example": "Please accept my apology.", "example_translation": "제 사과를 받아주세요." },
  "acceptable": { "example": "This behavior is not acceptable.", "example_translation": "이러한 행동은 용인될 수 없다." },
  "access": { "example": "We have internet access in the room.", "example_translation": "우리는 방에서 인터넷에 접속할 수 있다." },
  "accessibility": { "example": "The new ramp improved accessibility.", "example_translation": "새로운 경사로가 접근성을 향상시켰다." },
  "accessible": { "example": "The building is accessible to wheelchairs.", "example_translation": "그 건물은 휠체어로 출입할 수 있다." },
  "accidentally": { "example": "I accidentally deleted the file.", "example_translation": "실수로 파일을 삭제했다." },
  "acclaim": { "example": "The movie won critical acclaim.", "example_translation": "그 영화는 평론가들의 호평을 받았다." },
  "accommodate": { "example": "The hotel can accommodate 500 guests.", "example_translation": "그 호텔은 500명의 투숙객을 수용할 수 있다." },
  "accommodation": { "example": "We need to find accommodation for the night.", "example_translation": "우리는 하룻밤 묵을 숙소를 찾아야 한다." },
  "accompany": { "example": "I will accompany you to the station.", "example_translation": "역까지 동행하겠습니다." },
  "accompanying": { "example": "Please read the accompanying document.", "example_translation": "동봉된 문서를 읽어주세요." },
  "accomplish": { "example": "We can accomplish this task together.", "example_translation": "우리는 함께 이 일을 성취할 수 있다." },
  "accomplished": { "example": "She is an accomplished pianist.", "example_translation": "그녀는 노련한 피아니스트이다." },
  "accomplishment": { "example": "Winning the award was a great accomplishment.", "example_translation": "상을 받은 것은 큰 업적이었다." },
  "accord": { "example": "The two sides reached an accord.", "example_translation": "양측은 합의에 도달했다." },
  "account": { "example": "I opened a new bank account.", "example_translation": "나는 새 은행 계좌를 개설했다." },
  "accountable": { "example": "Managers must be accountable for their decisions.", "example_translation": "관리자들은 자신의 결정에 책임을 져야 한다." },
  "accountant": { "example": "She works as an accountant in a firm.", "example_translation": "그녀는 회사에서 회계사로 일한다." },
  "accounting": { "example": "He is studying accounting at university.", "example_translation": "그는 대학에서 회계학을 공부하고 있다." },
  "acculturation": { "example": "Acculturation takes time for immigrants.", "example_translation": "이민자들의 문화적 적응에는 시간이 걸린다." },
  "accumulate": { "example": "Dust began to accumulate on the shelf.", "example_translation": "선반에 먼지가 쌓이기 시작했다." },
  "accumulation": { "example": "The accumulation of wealth was his main goal.", "example_translation": "부의 축적이 그의 주된 목표였다." },
  "accurate": { "example": "Is this information accurate?", "example_translation": "이 정보는 정확합니까?" },
  "accurately": { "example": "The report accurately reflects the situation.", "example_translation": "그 보고서는 상황을 정확하게 반영한다." },
  "accuse": { "example": "They accuse him of stealing the money.", "example_translation": "그들은 그가 돈을 훔쳤다고 비난한다." },
  "accustomed": { "example": "I am accustomed to waking up early.", "example_translation": "나는 일찍 일어나는 데 익숙하다." },
  "achieve": { "example": "You can achieve anything if you try.", "example_translation": "노력하면 무엇이든 달성할 수 있다." },
  "achievement": { "example": "Graduating from college is a big achievement.", "example_translation": "대학 졸업은 큰 성취이다." },
  "acknowledge": { "example": "He refused to acknowledge his mistake.", "example_translation": "그는 자신의 실수를 인정하기를 거부했다." },
  "acquaint": { "example": "Please acquaint yourself with the rules.", "example_translation": "규칙을 숙지해 주십시오." },
  "acquire": { "example": "The company decided to acquire its rival.", "example_translation": "그 회사는 경쟁사를 인수하기로 결정했다." },
  "acquisition": { "example": "The acquisition of the new software improved productivity.", "example_translation": "새 소프트웨어의 구입은 생산성을 향상시켰다." },
  "act": { "example": "It is an act of kindness.", "example_translation": "그것은 친절한 행위이다." },
  "active": { "example": "She is very active in local politics.", "example_translation": "그녀는 지역 정치에 매우 적극적이다." },
  "activism": { "example": "Environmental activism is growing.", "example_translation": "환경 행동주의가 성장하고 있다." },
  "actually": { "example": "What actually happened that day?", "example_translation": "그날 실제로 무슨 일이 있었습니까?" },
  "acutely": { "example": "I am acutely aware of the problem.", "example_translation": "나는 그 문제를 절실히 인식하고 있다." },
  "adapt": { "example": "Animals must adapt to their environment.", "example_translation": "동물은 환경에 적응해야 한다." },
  "adaptation": { "example": "The movie is an adaptation of a famous novel.", "example_translation": "그 영화는 유명 소설의 각색판(적응)이다." },
  "additional": { "example": "We need additional time to finish the work.", "example_translation": "작업을 끝내려면 추가 시간이 필요합니다." },
  "additionally": { "example": "Additionally, it offers free shipping.", "example_translation": "게다가 무료 배송도 제공합니다." },
  "address": { "example": "We must address this issue immediately.", "example_translation": "우리는 이 문제를 즉시 다루어야 한다." },
  "adequacy": { "example": "They questioned the adequacy of the security.", "example_translation": "그들은 보안의 적절성에 의문을 제기했다." },
  "adequate": { "example": "Make sure you have an adequate supply of water.", "example_translation": "충분한 물을 공급받도록 하세요." },
  "adequately": { "example": "The problem was not adequately solved.", "example_translation": "문제가 적절히 해결되지 않았다." },
  "adhere": { "example": "You must adhere to the speed limit.", "example_translation": "당신은 제한 속도를 지켜야 합니다." },
  "adjacent": { "example": "They live in an adjacent building.", "example_translation": "그들은 인접한 건물에 산다." },
  "adjourn": { "example": "The meeting will adjourn at 5 PM.", "example_translation": "회의는 오후 5시에 휴회될 것이다." },
  "adjust": { "example": "It took time to adjust to the new school.", "example_translation": "새 학교에 적응하는 데 시간이 걸렸다." },
  "administrative": { "example": "She has administrative duties.", "example_translation": "그녀는 행정 업무를 맡고 있다." },
  "admiration": { "example": "I have great admiration for her work.", "example_translation": "나는 그녀의 작품에 대해 큰 존경심을 가지고 있다." },
  "admission": { "example": "Admission to the museum is free.", "example_translation": "박물관 입장은 무료입니다." },
  "adolescence": { "example": "Adolescence is a time of great change.", "example_translation": "청소년기는 큰 변화의 시기이다." },
  "adopt": { "example": "They decided to adopt a new strategy.", "example_translation": "그들은 새로운 전략을 채택하기로 결정했다." },
  "advance": { "example": "Technology continues to advance rapidly.", "example_translation": "기술은 계속해서 빠르게 진보한다." },
  "advanced": { "example": "This is a highly advanced computer system.", "example_translation": "이것은 고도로 진보한 컴퓨터 시스템이다." },
  "advantage": { "example": "The new method has a clear advantage.", "example_translation": "새로운 방법은 분명한 이점이 있다." },
  "advent": { "example": "The advent of the internet changed everything.", "example_translation": "인터넷의 출현은 모든 것을 바꾸었다." },
  "adversity": { "example": "She showed courage in the face of adversity.", "example_translation": "그녀는 역경 속에서도 용기를 보여주었다." },
  "advertise": { "example": "They advertise their products on television.", "example_translation": "그들은 텔레비전에 자사 제품을 광고한다." },
  "advertisement": { "example": "I saw an advertisement for a new job.", "example_translation": "나는 새 일자리 구인 광고를 보았다." },
  "advice": { "example": "He gave me some good advice.", "example_translation": "그는 내게 좋은 조언을 해주었다." },
  "advisable": { "example": "It is advisable to book early.", "example_translation": "일찍 예약하는 것이 바람직하다." },
  "advise": { "example": "I advise you to stay home.", "example_translation": "나는 당신에게 집에 머물 것을 충고합니다." },
  "advocate": { "example": "He is a strong advocate of animal rights.", "example_translation": "그는 강력한 동물 권리 옹호자이다." },
  "aesthetics": { "example": "The aesthetics of the building are beautiful.", "example_translation": "그 건물의 미학은 아름답다." },
  "affect": { "example": "The weather will affect our plans.", "example_translation": "날씨가 우리의 계획에 영향을 미칠 것이다." },
  "affix": { "example": "Please affix a stamp to the envelope.", "example_translation": "봉투에 우표를 붙여주세요." },
  "affordability": { "example": "Housing affordability is a major issue.", "example_translation": "주택의 감당 가능한 비용이 주요 문제이다." },
  "affordable": { "example": "They offer affordable prices.", "example_translation": "그들은 알맞은 가격을 제공한다." },
  "age": { "example": "The building began to age quickly.", "example_translation": "그 건물은 빠르게 노후화되기 시작했다." },
  "agency": { "example": "She works for an advertising agency.", "example_translation": "그녀는 광고 대행 회사에서 일한다." },
  "agenda": { "example": "What is on the agenda for today's meeting?", "example_translation": "오늘 회의의 의제는 무엇입니까?" },
  "aggravate": { "example": "Stress can aggravate the condition.", "example_translation": "스트레스는 상태를 악화시킬 수 있다." },
  "aggression": { "example": "The dog showed signs of aggression.", "example_translation": "그 개는 공격의 징후를 보였다." },
  "aggressively": { "example": "The company marketed its product aggressively.", "example_translation": "그 회사는 제품을 적극적으로 마케팅했다." },
  "agree": { "example": "I agree with your opinion.", "example_translation": "나는 당신의 의견에 동의한다." },
  "agreeable": { "example": "We spent an agreeable afternoon together.", "example_translation": "우리는 기분 좋은 오후를 함께 보냈다." },
  "agreement": { "example": "They signed an agreement.", "example_translation": "그들은 협정에 서명했다." },
  "agricultural": { "example": "It is an agricultural community.", "example_translation": "그곳은 농업 공동체이다." },
  "agriculture": { "example": "Agriculture is the basis of their economy.", "example_translation": "농업은 그들 경제의 기반이다." },
  "ahistorical": { "example": "His view of the event is purely ahistorical.", "example_translation": "그 사건에 대한 그의 견해는 순전히 몰역사적이다." },
  "aid": { "example": "The country provided military aid.", "example_translation": "그 국가는 군사적 원조를 제공했다." },
  "aim": { "example": "Her aim is to become a doctor.", "example_translation": "그녀의 목표는 의사가 되는 것이다." },
  "aimlessly": { "example": "He wandered aimlessly around the city.", "example_translation": "그는 목적 없이 도시 주변을 배회했다." },
  "algorithm": { "example": "The computer uses a complex algorithm.", "example_translation": "그 컴퓨터는 복잡한 알고리즘을 사용한다." }
};

const filePath = path.join(__dirname, 'src', 'data', 'seedWords.json');
let data = require(filePath);

let updated = 0;
data = data.map(word => {
  if (examples[word.english]) {
    updated++;
    return {
      ...word,
      example: examples[word.english].example,
      example_translation: examples[word.english].example_translation
    };
  }
  return word;
});

fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
console.log(`Successfully added examples to ${updated} words.`);
